services:

  load-balancer:
    container_name: load-balancer
    image: nginx:1.28.0-alpine
    user: "0:0"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/docker-entrypoint.d/set-sock-permissions.sh:/docker-entrypoint.d/set-sock-permissions.sh:ro
      - sockets:/run:rw   
    ports:
      - "9999:9999"
    depends_on:
      - api-1
      - api-2
    networks:
      - backend
    deploy:
      resources:
        limits:
          cpus: "0.2"
          memory: "40MB"
  api-1:
    container_name: api-1
    hostname: api1
    volumes:
      - sockets:/run:rw
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SERVER_NAME=api1
      - MAX_DEGREE_OF_PARALLELISM=10
      - DEFAULT_BASE_URL=http://payment-processor-default:8080
      - FALLBACK_BASE_URL=http://payment-processor-fallback:8080
      - OTHER_SERVER=api2
      - MASTER_HEALTH_CHECK=true
    ports:
      - "5001:8080"
    networks:
      - backend
      - payment-processor
    healthcheck:
      test: curl --fail http://localhost:8080/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s        
    deploy:
      resources:
        limits:
          cpus: "0.7"
          memory: "155MB"
  api-2:
    container_name: api-2
    hostname: api2
    volumes:
      - sockets:/run:rw    
    build:
      context: ./src
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - SERVER_NAME=api2
      - MAX_DEGREE_OF_PARALLELISM=10
      - DEFAULT_BASE_URL=http://payment-processor-default:8080
      - FALLBACK_BASE_URL=http://payment-processor-fallback:8080
      - OTHER_SERVER=api1
      - MASTER_HEALTH_CHECK=false      
    ports:
      - "5002:8080"
    networks:
      - backend
      - payment-processor
    healthcheck:
      test: curl --fail http://localhost:8080/ || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s      
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "155MB"        
volumes:
  sockets:

networks:
  backend:
    name: backend
    driver: bridge
  payment-processor:
    name: payment-processor
    driver: bridge
    external: true                